trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  storageAccountName: 'expensetracker2026kartik'

steps:

# =========================
# CI - Validate application
# =========================

- checkout: self

- script: |
    echo "Checking Expense Tracker files..."

    test -f index.html
    test -f css/style.css
    test -f js/app.js
    test -f js/storage.js

    echo "All required files are present."
  displayName: 'Validate Expense Tracker'


# =========================
# CD - Deploy to Azure
# =========================

- task: AzureCLI@2
  displayName: 'Deploy Expense Tracker to Azure Storage'
  inputs:
    azureSubscription: 'ExpenseTracker-Azure'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Deploying Expense Tracker..."

      STORAGE_KEY=$(az storage account keys list \
        --resource-group rg-expense-tracker \
        --account-name "$(storageAccountName)" \
        --query "[0].value" \
        --output tsv)

      az storage blob upload-batch \
        --account-name "$(storageAccountName)" \
        --account-key "$STORAGE_KEY" \
        --destination '$web' \
        --source "$(Build.SourcesDirectory)" \
        --overwrite true

      echo "Deployment completed successfully."