trigger:
  - main

pool:
  name: Default

stages:

# =========================
# CI - Validate
# =========================
- stage: CI
  displayName: 'CI - Validate Expense Tracker'

  jobs:
  - job: Validate
    displayName: 'Validate Files'

    steps:
    - checkout: self

    - powershell: |
        Write-Host "Checking Expense Tracker files..."

        $files = @(
          "index.html",
          "css/style.css",
          "js/app.js",
          "js/storage.js"
        )

        foreach ($file in $files) {
          if (-not (Test-Path $file)) {
            Write-Error "Missing required file: $file"
            exit 1
          }
        }

        Write-Host "All required files are present."
      displayName: 'Validate Expense Tracker'


# =========================
# CD - Deploy to Azure
# =========================
- stage: CD
  displayName: 'CD - Deploy to Azure'

  dependsOn: CI
  condition: succeeded()

  jobs:
  - job: Deploy
    displayName: 'Deploy to Azure Storage'

    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: 'Deploy Expense Tracker to Azure Storage'
      inputs:
        azureSubscription: 'ExpenseTracker-Azure'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          Write-Host "Deploying Expense Tracker to Azure Storage..."

          az storage blob upload-batch `
            --account-name expensetracker2026cicd `
            --destination '$web' `
            --source "$(Build.SourcesDirectory)" `
            --auth-mode login `
            --overwrite

          Write-Host "Deployment completed successfully!"